# Generated by Django 5.1.6 on 2025-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='viesws',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
