# Generated by Django 5.1.6 on 2025-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_news_viesws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='viesws',
            field=models.IntegerField(default=0),
        ),
    ]
